// <auto-generated />
using System;
using EsxiRestfulApi.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace EsxiRestfulApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191219001656_InitialEntities")]
    partial class InitialEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("EsxiRestfulApi.Database.Models.Filesystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Free")
                        .HasColumnType("text");

                    b.Property<bool>("Mounted")
                        .HasColumnType("boolean");

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.Property<string>("VolumeName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Filesystems");
                });

            modelBuilder.Entity("EsxiRestfulApi.Database.Models.PortGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActiveClients")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("VLANId")
                        .HasColumnType("integer");

                    b.Property<Guid>("VSwitchId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VSwitchId");

                    b.ToTable("PortGroups");
                });

            modelBuilder.Entity("EsxiRestfulApi.Database.Models.VSwitch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BeaconEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("BeaconInterval")
                        .HasColumnType("integer");

                    b.Property<string>("BeaconRequiredBy")
                        .HasColumnType("text");

                    b.Property<int>("BeaconThreshold")
                        .HasColumnType("integer");

                    b.Property<string>("CDPStatus")
                        .HasColumnType("text");

                    b.Property<string>("Class")
                        .HasColumnType("text");

                    b.Property<int>("ConfiguredPorts")
                        .HasColumnType("integer");

                    b.Property<int>("MTU")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("NumPorts")
                        .HasColumnType("integer");

                    b.Property<string>("Uplinks")
                        .HasColumnType("text");

                    b.Property<int>("UsedPorts")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("VSwitches");
                });

            modelBuilder.Entity("EsxiRestfulApi.Database.Models.PortGroup", b =>
                {
                    b.HasOne("EsxiRestfulApi.Database.Models.VSwitch", "VSwitch")
                        .WithMany("PortGroups")
                        .HasForeignKey("VSwitchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
